services:
  api:
    image: viet-tts:latest
    build: .
    restart: always
    container_name: viet-tts-service
    ports:
      - 8298:8298
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./pretrained-models:/app/pretrained-models
    command: viettts server --host 0.0.0.0 --port 8298